# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireworder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_status',
            field=models.CharField(default='on', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='f1_status',
            field=models.CharField(default='on', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='movie_status',
            field=models.CharField(default='on', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='room_status',
            field=models.CharField(default='on', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='stock_status',
            field=models.CharField(default='on', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='verge_status',
            field=models.CharField(default='on', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='wheater_city',
            field=models.CharField(default='Eindhoven', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='wheater_degree',
            field=models.CharField(default='on', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='wheater_satus',
            field=models.CharField(default='on', max_length=10),
        ),
    ]
