# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireworder', '0002_auto_20171201_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1_round', models.TextField(blank=True, null=True)),
                ('f1_season', models.TextField(blank=True, null=True)),
                ('f1_wiki', models.TextField(blank=True, null=True)),
                ('f1_name', models.TextField(blank=True, null=True)),
                ('movie_poster', models.TextField(blank=True, null=True)),
                ('movie_vote', models.TextField(blank=True, null=True)),
                ('movie_title', models.TextField(blank=True, null=True)),
                ('movie_overview', models.TextField(blank=True, null=True)),
                ('verge_author', models.TextField(blank=True, null=True)),
                ('verge_title', models.TextField(blank=True, null=True)),
                ('verge_description', models.TextField(blank=True, null=True)),
                ('verge_url', models.TextField(blank=True, null=True)),
                ('verge_image', models.TextField(blank=True, null=True)),
                ('wheater_cirtykey', models.TextField(blank=True, null=True)),
                ('wheater_country', models.TextField(blank=True, null=True)),
                ('wheater_province', models.TextField(blank=True, null=True)),
                ('wheater_dailyforecasts', models.TextField(blank=True, null=True)),
                ('daily_imageurl', models.TextField(blank=True, null=True)),
                ('daily_imagelink', models.TextField(blank=True, null=True)),
                ('stock_companyname', models.TextField(blank=True, null=True)),
                ('stock_exchange', models.TextField(blank=True, null=True)),
                ('stock_price', models.TextField(blank=True, null=True)),
                ('stock_changepercent', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
