# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-09 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireworder', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='wheater_day2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_today',
            field=models.TextField(blank=True, null=True),
        ),
    ]
