# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-09 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireworder', '0004_auto_20171209_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='wheater_today',
            new_name='wheater_day1',
        ),
    ]
