# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-09 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireworder', '0005_auto_20171209_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='wheater_day1',
        ),
        migrations.RemoveField(
            model_name='data',
            name='wheater_day3',
        ),
        migrations.RemoveField(
            model_name='data',
            name='wheater_day4',
        ),
        migrations.RemoveField(
            model_name='data',
            name='wheater_day5',
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day1_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day1_max',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day1_min',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day2_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day2_max',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day2_min',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day3_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day3_max',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day3_min',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day4_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day4_max',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day4_min',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day5_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day5_max',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='wheater_day5_min',
            field=models.TextField(blank=True, null=True),
        ),
    ]
