# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-09 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireworder', '0007_data_wheater_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='f1_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='f1_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
